#!/bin/bash
set -e

# This file is generated by `build` in linglong.yaml
# DO NOT EDIT IT

# enable strip symbols
export CFLAGS="-g $CFLAGS"
export CXXFLAGS="-g $CFLAGS"
# 修改路径
sed -i "s|/usr|$PREFIX|g" src/libdmusic/CMakeLists.txt

# 构建
VERSION=$(head -1 debian/changelog | awk -F'[()]' '{print $2}')
cmake -B build \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=${PREFIX} \
    -DCMAKE_INSTALL_LIBDIR=${PREFIX}/lib/${TRIPLET} \
    -DAPP_VERSION=${VERSION} \
    -DVERSION=${VERSION}
cmake --build build -j`nproc`
cmake --build build --target install > install.log 2>&1
# update for libdmusic.so
ldconfig -C "$LINGLONG_LD_SO_CACHE"

# POST BUILD PROCESS
/usr/libexec/linglong/builder/helper/symbols-strip.sh
